sudo: required
services:
  - docker

before_install:
  - docker build -t my-react -f Dockerfile.dev .

script:
  - node -v
  - docker run my-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-730906163856"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"